version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend-dev
    container_name: frontend-dev
    command: npm start
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/home/app/frontend
      - /home/app/frontend/node_modules     # copies folder in IMAGE and binds it to container
